### ISSUE TITLE
[US_ID][Pre-launch] Get data for Recidivism charts on Prison narrative

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/public-dashboard#585] opened 2022-07-18 00:12 UTC
**Describe the bug**
The two Recidivism sections on the Prison narrative don't work because we currently don't have the data for them.

**To Reproduce**
1. Go to https://spotlight-staging.recidiviz.org/us-id/narratives/prison/7 (and scroll down to https://spotlight-staging.recidiviz.org/us-id/narratives/prison/8)
2. See "Some data could not be loaded because of an error."

**Additional context**
This is because we are missing the relevant metric files in our GCS bucket [here](https://console.cloud.google.com/storage/browser/recidiviz-staging-public-dashboard-data/US_ID;tab=objects?project=recidiviz-staging&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false). We need to hook up this query [here](https://console.cloud.google.com/bigquery?project=recidiviz-staging&ws=!1m10!1m4!4m3!1srecidiviz-123!2sanalyst_data_scratch_space!3ssession_cohort_reincarceration_spotlight!1m4!1m3!1srecidiviz-staging!2sbquxjob_42855058_181b0bd70b2!3sUS).

**Comment by jkgerig** [comment] 2022-07-18 16:51
Duplicate of Recidiviz/recidiviz-data#13467

**Closed by jkgerig** 2022-07-18 16:51 UTC
Labels: State Pod: MINDMELD
